version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - root/SprinProject-0.0.1-SNAPSHOT.war
